export const ITEM_LABELS: Record<string, string> = {
  wood: "나무",
  hardwood: "단단한 나무",
  stone: "돌",
  fiber: "섬유",
  ore: "광석",
  berry: "열매",
  herb: "약초",
  coal: "석탄",
  ice_crystal: "얼음 결정",
  ember_shard: "불씨 조각",
  pal_essence: "펄 정수",
  leaf_pelt: "잎사귀 털가죽",
  flame_tail: "불꽃 꼬리털",
  water_jelly: "물방울 젤리",
  spark_core: "전기 코어",
  ingot: "주괴",
  refined_ingot: "정제 주괴",

  capture_orb: "포획구",
  improved_capture_orb: "개량 포획구",
  berry_meal: "열매 식사",
  cooked_berry: "구운 열매",
  warm_meal: "따뜻한 식사",
  healing_salve: "회복 연고",

  basic_axe: "기본 도끼",
  basic_pickaxe: "기본 곡괭이",
  basic_sickle: "기본 낫",
  training_sword: "훈련용 검",
  iron_sword: "철검",
  explorer_jacket: "탐험가 재킷",
  leather_boots: "가죽 장화",
  thermal_jacket: "방열 재킷",
  cooling_charm: "냉각 부적",
  pal_work_harness: "펄 작업 하네스",
  leafbun_saddle: "풀토끼 안장",
  mossboar_saddle: "이끼멧돼지 안장",
  frosthorn_saddle: "서리뿔 안장",

  workbench: "작업대",
  campfire: "모닥불",
  storage_box: "보관함",
  base_core: "거점 코어",
  pal_bed: "펄 침대",
  farm_plot: "작은 밭",
  wood_floor: "나무 바닥",
  wood_wall: "나무 벽",
  furnace: "화로",
  advanced_workbench: "고급 작업대",
  kitchen: "조리대",
  guard_tower: "감시탑",
  assembly_bench: "조립대",
  power_generator: "발전기",
  cold_storage: "냉장 보관함",

  workbench_kit: "작업대 키트",
  base_core_kit: "거점 코어 키트",
};

export function getItemLabel(itemId: string) {
  return ITEM_LABELS[itemId] ?? itemId;
}
